export type IssueSeverity = 'error' | 'warning' | 'info';
export type VerifyDimension = 'completeness' | 'correctness' | 'coherence' | 'vault_integrity';

/**
 * Central taxonomy of verify issue codes.
 * AI agents and automation should branch on these values.
 */
export const VERIFY_CODES = {
  // completeness
  MISSING_SECTION: 'MISSING_SECTION',
  MISSING_REQUIREMENTS: 'MISSING_REQUIREMENTS',
  MISSING_DELTA_SUMMARY: 'MISSING_DELTA_SUMMARY',
  MISSING_TASKS: 'MISSING_TASKS',
  MISSING_VALIDATION: 'MISSING_VALIDATION',
  MISSING_LINK: 'MISSING_LINK',
  MISSING_DESIGN_APPROACH: 'MISSING_DESIGN_APPROACH',
  EMPTY_REQUIRED_SECTION: 'EMPTY_REQUIRED_SECTION',

  // correctness
  INVALID_FRONTMATTER_REF: 'INVALID_FRONTMATTER_REF',
  DELTA_MISMATCH_ADDED: 'DELTA_MISMATCH_ADDED',
  DELTA_MISMATCH_MODIFIED: 'DELTA_MISMATCH_MODIFIED',
  DELTA_MISMATCH_REMOVED: 'DELTA_MISMATCH_REMOVED',
  DELTA_MISMATCH_RENAMED: 'DELTA_MISMATCH_RENAMED',
  MODIFIED_NO_CHANGE: 'MODIFIED_NO_CHANGE',
  STALE_BASE: 'STALE_BASE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  BROKEN_DEPENDS_ON: 'BROKEN_DEPENDS_ON',
  INVALID_DEPENDS_ON_TYPE: 'INVALID_DEPENDS_ON_TYPE',
  SCHEMA_MISMATCH: 'SCHEMA_MISMATCH',
  UNSUPPORTED_SCHEMA_VERSION: 'UNSUPPORTED_SCHEMA_VERSION',
  BREAKING_CHANGE_WITHOUT_VERSION_BUMP: 'BREAKING_CHANGE_WITHOUT_VERSION_BUMP',
  EXCESSIVE_DRIFT: 'EXCESSIVE_DRIFT',
  UNFILLED_APPLY_MARKER: 'UNFILLED_APPLY_MARKER',

  // coherence
  TOUCHES_OVERLAP_BLOCKED: 'TOUCHES_OVERLAP_BLOCKED',
  TOUCHES_OVERLAP_CONFLICT: 'TOUCHES_OVERLAP_CONFLICT',
  TOUCHES_OVERLAP_NEEDS_REVIEW: 'TOUCHES_OVERLAP_NEEDS_REVIEW',
  REQUIREMENT_CONFLICT_CRITICAL: 'REQUIREMENT_CONFLICT_CRITICAL',
  DEPENDENCY_CYCLE: 'DEPENDENCY_CYCLE',
  OUT_OF_ORDER: 'OUT_OF_ORDER',
  CONFLICTING_DESCRIPTIONS: 'CONFLICTING_DESCRIPTIONS',
  INCONSISTENT_DECISION: 'INCONSISTENT_DECISION',

  // vault_integrity
  DUPLICATE_ID: 'DUPLICATE_ID',
  MISSING_ID: 'MISSING_ID',
  UNRESOLVED_WIKILINK: 'UNRESOLVED_WIKILINK',
  AMBIGUOUS_ALIAS: 'AMBIGUOUS_ALIAS',
  ORPHAN_NOTE: 'ORPHAN_NOTE',
  ARCHIVE_PLACEMENT_ERROR: 'ARCHIVE_PLACEMENT_ERROR',
  EMPTY_TYPED_NOTE: 'EMPTY_TYPED_NOTE',
  TITLE_ID_COLLISION: 'TITLE_ID_COLLISION',
  POTENTIAL_SECRET_LEAK: 'POTENTIAL_SECRET_LEAK',
  TYPE_FOLDER_MISMATCH: 'TYPE_FOLDER_MISMATCH',
  APPLY_IN_PROGRESS: 'APPLY_IN_PROGRESS',
  ARCHIVED_TARGET: 'ARCHIVED_TARGET',
} as const;

export type VerifyCode = typeof VERIFY_CODES[keyof typeof VERIFY_CODES];

export interface VerifyIssue {
  dimension: VerifyDimension;
  severity: IssueSeverity;
  code: VerifyCode | string;
  message: string;
  note_path?: string;
  note_id?: string;
  suggestion?: string;
}

/**
 * JSON contract version for VerifyReport. Bump this when the shape of the
 * report changes in a way that breaks existing consumers.
 */
export const VERIFY_REPORT_SCHEMA_VERSION = '1.0.0';

export interface VerifyReport {
  /** Schema version for the report JSON contract. See VERIFY_REPORT_SCHEMA_VERSION. */
  schema_version?: string;
  scanned_at: string;
  total_notes: number;
  issues: VerifyIssue[];
  summary: Record<VerifyDimension, { errors: number; warnings: number; info: number }>;
  pass: boolean;
}
